[functions]
  directory = "functions"

[build]
    functions = "functions"
    publish = "dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
    for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"